spring:
  application:
    name: hystrixFeign-producer
server:
  port: 8081
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true # \u542F\u7528ip\u914D\u7F6E \u8FD9\u6837\u5728\u6CE8\u518C\u4E2D\u5FC3\u5217\u8868\u4E2D\u770B\u89C1\u7684\u662F\u4EE5ip+\u7AEF\u53E3\u5448\u73B0\u7684
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
