spring:
  application:
    name: demo-client

server:
  port: 8081

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true # 启用ip配置 这样在注册中心列表中看见的是以ip+端口呈现的
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    #register-with-eureka: false # 不要向注册中心注册自己

    ## 表示不去检索其他的服务，因为服务注册中心本身的职责就是维护服务实例，它也不需要去检索其他服务
    #eureka.client.fetch-registry=false
