server:
  port: 7777

spring:
  application:
    name: ribbon-client
eureka:
  client:
    serviceUrl:
         defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true # 启用ip配置 这样在注册中心列表中看见的是以ip+端口呈现的

test-client:
  ribbon:
    listOfServers: http://localhost:7071,http://localhost:7072 #ribbon脱离eureka的使用，这里指定源服务列表
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule #声明策略模式为随机
  eager-load:
      clients:
      enabled: #使用配置的方式对特定的源服务进行策略约束【规则：clientName.ribbon.*】
ribbon:
  eureka:
    enabled: false #禁用eureka
